spring:
  profiles:
    active: prod

server:
  port: 5000

app:
  datasource:
    jdbc-url: jdbc:${JDBC_DATABASE_URL}
    username: paatijsmvjgmcq
    password: ${DATABASE_PASSWORD}
    pool-size: 30